In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from tqdm import tqdm
from glob import glob
import os
import json 
import torch
from torch import nn
from torchvision import models
from torch.utils.data import Dataset
# from sklearn.metrics import f1_score
# from sklearn.model_selection import train_test_split

In [2]:
import os
import sys
os.environ["CUDA_VISIBLE_DEVICES"]="7"

In [37]:
# aws csv 데이터에 위도, 경도, 해발고도, 지점번호와 매칭되는 해당 권역 추가

sample_csv = pd.read_csv('/raid/workspace/honghee/data_weather/train_x/aws/2014/201407.csv')
target_csv = pd.read_csv('/raid/workspace/honghee/data_weather/train_y/weather_news/2014_2020_target.csv')
# target_csv
# list(target_csv.columns)
print(list(sample_csv.columns))
# print(sample_csv)
region_csv = pd.read_csv('/raid/workspace/honghee/data_weather/train_x/aws/region_filled.csv')
region_csv = region_csv[['지점', '지점주소', '위도', '경도', '노장해발고도(m)']][0:628]
region_csv['권역'] = region_csv['지점주소'].astype(str).str[0:3]
region_csv = region_csv.drop('지점주소', axis=1)
# print(region_csv)

do_list = []
latitude_list = []
longtitude_list = []
elevation_list = []
for i in range(len(sample_csv)):
    region = sample_csv.loc[i, '지점번호']
    if region_csv.index[region_csv['지점'] == region].tolist() == []:
#         print("empty:", region)
        do_list.append('none')
        latitude_list.append('none')
        longtitude_list.append('none')
        elevation_list.append('none')
    else:
        region_index = region_csv.index[region_csv['지점'] == region].tolist()[0]
        do = region_csv.loc[region_index, '권역']
        latitude = region_csv.loc[region_index, '위도']
        longtitude = region_csv.loc[region_index, '경도']
        elevation = region_csv.loc[region_index, '노장해발고도(m)']
#     if region_csv.index[region_csv['지점'] == region].tolist() == []:
#         print(region)
#         print(region_index)
#         print(do)
        do_list.append(do)
        latitude_list.append(latitude)
        longtitude_list.append(longtitude)
        elevation_list.append(elevation)
# print('final: ', temp[0], temp[1234], temp[3425], temp[83279], temp[43857], temp[100000], temp[-1])        
sample_csv['위도']=latitude_list
sample_csv['경도']=longtitude_list
sample_csv['해발고도']=elevation_list
sample_csv['권역']=do_list
sample_csv = sample_csv.drop(sample_csv[sample_csv.권역 == 'none'].index)
# print(sample_csv)
sample_csv.to_csv("/raid/workspace/honghee/data_weather/train_x/aws/sample.csv", index=False)

['Unnamed: 0', '지점번호', '시각', '평균 기온', '최고 기온', '최저 기온', '평균 풍속', '합성 풍속', '합성 풍향', '최대 순간 풍속', '최대 순간 풍속 풍향', '평균 전운량', '합계 강수량', '평균 현지기압', '평균 해면기압', '이슬점온도', '10분 평균 시정', '운고']

In [12]:
import pandas as pd

df = pd.DataFrame({'year':['2012', '2011'], 'month':['01', '02'], '1':['5', '5'], '2':['98', '76'], '3':['54', '32'], '4':['54', '32']})
df['concatenated']=  df['year']
df['concat']=  df['2']
for i in range(2):
    df['concatenated'] += df.iloc[:, i+1]
    df['concat'] += df.iloc[:, i+4]
df['concatenated'] = df.concatenated.apply(lambda x: list(x))
print(df)
print(df.iloc[0,1])
x= list(df.columns)
print(x)
label_x = df.index[df['year'] == '2012'].tolist()[0]
print(label_x)
label_y = [i for i in range(len(x)) if 'mo' in x[i]][0]
print(label_y)
    
label = df.iloc[label_x, label_y]
print(label)

   year month  1   2   3   4           concatenated  concat
0  2012    01  5  98  54  54  [2, 0, 1, 2, 0, 1, 5]  985454
1  2011    02  5  76  32  32  [2, 0, 1, 1, 0, 2, 5]  763232
01
['year', 'month', '1', '2', '3', '4', 'concatenated', 'concat']
0
1
01

In [12]:
# target_csv 를 9개 권역, 권역당 13개의 label을 원핫으로 바꿔서 저장

target_csv = pd.read_csv('/raid/workspace/honghee/data_weather/train_y/weather_news/2014_2020_target.csv')
# print(target_csv)
# d = target_csv.where(target_csv==0)
# d = target_csv[target_csv['서울·인천·경기도_호우']==1]
# print(d)
# print(d.to_numpy().sum())
# target_csv = target_csv.astype(str)
# print(list(target_csv.columns))
target_csv["서울특인천광경기도"] = target_csv["서울·인천·경기도_강풍"].astype(str)
target_csv["부산광울산광경상남"] = target_csv["부산·울산·경상남도_강풍"].astype(str)
target_csv["대구광경상북"] = target_csv["대구·경상북도_강풍"].astype(str)
target_csv["광주광전라남"] = target_csv["광주·전라남도_강풍"].astype(str)
target_csv["전라북"] = target_csv["전라북도_강풍"].astype(str)
target_csv["대전광세종특충청남"] = target_csv["대전·세종·충청남도_강풍"].astype(str)
target_csv["충청북"] = target_csv["충청북도_강풍"].astype(str)
target_csv["강원도"] = target_csv["강원도_강풍"].astype(str)
target_csv["제주도"] = target_csv["제주도_강풍"].astype(str)


for i in range(12):
    target_csv["서울특인천광경기도"] += target_csv.iloc[:, i+1].astype(str)
    target_csv["부산광울산광경상남"] += target_csv.iloc[:, i+14].astype(str)
    target_csv["대구광경상북"] += target_csv.iloc[:, i+27].astype(str)
    target_csv["광주광전라남"] += target_csv.iloc[:, i+40].astype(str)
    target_csv["전라북"] += target_csv.iloc[:, i+53].astype(str)
    target_csv["대전광세종특충청남"] += target_csv.iloc[:, i+66].astype(str)
    target_csv["충청북"] += target_csv.iloc[:, i+79].astype(str)
    target_csv["강원도"] += target_csv.iloc[:, i+92].astype(str)
    target_csv["제주도"] += target_csv.iloc[:, i+105].astype(str)
target_csv['서울특인천광경기도'] = target_csv.서울특인천광경기도.apply(lambda x: list(x))
target_csv['부산광울산광경상남'] = target_csv.부산광울산광경상남.apply(lambda x: list(x))
target_csv['대구광경상북'] = target_csv.대구광경상북.apply(lambda x: list(x))
target_csv['광주광전라남'] = target_csv.광주광전라남.apply(lambda x: list(x))
target_csv['전라북'] = target_csv.전라북.apply(lambda x: list(x))
target_csv['대전광세종특충청남'] = target_csv.대전광세종특충청남.apply(lambda x: list(x))
target_csv['충청북'] = target_csv.충청북.apply(lambda x: list(x))
target_csv['강원도'] = target_csv.강원도.apply(lambda x: list(x))
target_csv['제주도'] = target_csv.제주도.apply(lambda x: list(x))
target = target_csv.iloc[:, 131:140]
# print(target.iloc[1,1])
# print(target)
target.to_csv("/raid/workspace/honghee/data_weather/train_y/weather_news/target.csv", index=False)
# label = pd.read_csv("/raid/workspace/honghee/data_weather/train_y/weather_news/target.csv")
# print(label)

                                               서울특인천광경기도  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

                                               부산광울산광경상남  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '1', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '1', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

                                                  대구광경상북  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...

                                                  광주광전라남  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

                                                     전라북  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

                                               대전광세종특충청남  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

                                                     충청북  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

                                                     강원도  \
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '2', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '2', '0', '0', '0', '1', '0', '0', ...
52607  ['0', '0', '2', '0', '0', '0', '1', '0', '0', ...

                                                     제주도
0      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4      ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                  ...
52603  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52604  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52605  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52606  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
52607  ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...

[52608 rows x 9 columns]

In [19]:
# aws 데이터에서 target csv의 label과 매칭되는 시각, 권역의 row에 해당 label 추가

target_csv = pd.read_csv('/raid/workspace/honghee/data_weather/train_y/weather_news/2014_2020_target.csv')
label_csv = pd.read_csv("/raid/workspace/honghee/data_weather/train_y/weather_news/target.csv")
label_csv["시각"] = target_csv["datetime"]
# print(label_csv)
sample_csv = pd.read_csv("/raid/workspace/honghee/data_weather/train_x/aws/sample.csv")
sample_csv = sample_csv.drop('Unnamed: 0', axis=1)
sample_csv = sample_csv.replace('제주특', '제주도')
sample_csv = sample_csv.replace('서귀포', '제주도')
# print(sample_csv)
# sys.exit()

label_list = []
label_names = list(label_csv.columns)
# print(label_names)
for i in range(len(sample_csv)):
#     print(i)
    time = sample_csv.loc[i, '시각']  # time
    region_name = sample_csv.loc[i, '권역']  # 제주특
#     print("time: ", time)
#     print("region: ", region_name)
    label_x = label_csv.index[label_csv['시각'] == time].tolist()[0]
#     print(label_x)
    label_y = [i for i in range(len(label_names)) if region_name in label_names[i]][0]
#     print(label_y)
    label = label_csv.iloc[label_x, label_y]
#     label = label_csv.iloc[label_x, label_y].values[0][0]
#     print(label)
    label_list.append(label)

sample_csv['weather_label']=label_list
print(sample_csv)
sample_csv.to_csv("/raid/workspace/honghee/data_weather/train_x/aws/201407.csv", index=False)

        지점번호                   시각  평균 기온  최고 기온  최저 기온  평균 풍속  합성 풍속  합성 풍향  \
0         90  2014-07-01 01:00:00   20.3   20.5   20.0    0.7    0.6  285.6
1         90  2014-07-01 02:00:00   20.1   20.3   19.9    0.8    0.7  310.0
2         90  2014-07-01 03:00:00   19.9   20.0   19.7    1.2    1.1  306.1
3         90  2014-07-01 04:00:00   19.6   19.7   19.4    0.4    0.2  353.8
4         90  2014-07-01 05:00:00   19.5   19.7   19.3    0.5    0.4  325.3
...      ...                  ...    ...    ...    ...    ...    ...    ...
467227   989  2014-07-31 20:00:00    NaN    NaN    NaN    NaN    NaN    NaN
467228   989  2014-07-31 21:00:00    NaN    NaN    NaN    NaN    NaN    NaN
467229   989  2014-07-31 22:00:00    NaN    NaN    NaN    NaN    NaN    NaN
467230   989  2014-07-31 23:00:00    NaN    NaN    NaN    NaN    NaN    NaN
467231   989  2014-08-01 00:00:00    NaN    NaN    NaN    NaN    NaN    NaN

        최대 순간 풍속  최대 순간 풍속 풍향  ...  평균 현지기압  평균 해면기압  이슬점온도  10분 평균 시정  \
0            1.7        315.0  ...   1006.9   1009.0   20.1        NaN
1            1.7        275.6  ...   1007.2   1009.3   19.9        NaN
2            2.5        334.7  ...   1007.4   1009.5   19.6        NaN
3            1.6        208.1  ...   1007.6   1009.7   19.5        NaN
4            1.2          0.0  ...   1008.2   1010.3   19.2        NaN
...          ...          ...  ...      ...      ...    ...        ...
467227       NaN          NaN  ...      NaN      NaN    NaN        NaN
467228       NaN          NaN  ...      NaN      NaN    NaN        NaN
467229       NaN          NaN  ...      NaN      NaN    NaN        NaN
467230       NaN          NaN  ...      NaN      NaN    NaN        NaN
467231       NaN          NaN  ...      NaN      NaN    NaN        NaN

            운고       위도        경도   해발고도   권역  \
0       7620.0  38.2509  128.5647  17.53  강원도
1       7620.0  38.2509  128.5647  17.53  강원도
2         45.0  38.2509  128.5647  17.53  강원도
3         45.0  38.2509  128.5647  17.53  강원도
4         45.0  38.2509  128.5647  17.53  강원도
...        ...      ...       ...    ...  ...
467227     NaN  33.2579  126.3299  90.00  제주도
467228     NaN  33.2579  126.3299  90.00  제주도
467229     NaN  33.2579  126.3299  90.00  제주도
467230     NaN  33.2579  126.3299  90.00  제주도
467231     NaN  33.2579  126.3299  90.00  제주도

                                            weather_label
0       ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
1       ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
2       ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
3       ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
4       ['0', '0', '0', '0', '0', '0', '0', '0', '0', ...
...                                                   ...
467227  ['0', '0', '1', '0', '0', '0', '0', '0', '0', ...
467228  ['0', '0', '1', '0', '0', '0', '0', '0', '0', ...
467229  ['0', '0', '1', '1', '0', '0', '0', '0', '0', ...
467230  ['0', '0', '1', '1', '0', '0', '0', '0', '0', ...
467231  ['0', '0', '1', '1', '0', '0', '0', '0', '0', ...

[467232 rows x 22 columns]

In [51]:
# 같은 지점끼리 모은 후 결측값 linear interpolation 처리 

aws1 = pd.read_csv("/raid/workspace/honghee/data_weather/train_x/aws/201407.csv")
regionlist_csv = pd.read_csv('/raid/workspace/honghee/data_weather/train_x/aws/region_filled.csv')
regionlist = regionlist_csv['지점'][0:628].tolist()
for r in regionlist:
    y = aws1.loc[aws1['지점번호'] == r]
    globals()[f'aws_{int(r)}'] = y # aws_지점번호 인 csv 생성
    globals()[f'aws_{int(r)}'] =  globals()[f'aws_{int(r)}'].interpolate()
#     globals()[f'aws_{int(r)}'] =  globals()[f'aws_{int(r)}'].interpolate().fillna(method='bfill')
#     break
# print(aws_989) 
aws = pd.DataFrame()
for r in regionlist:
    aws = pd.concat([aws, globals()[f'aws_{int(r)}']])
aws = aws.fillna(0) 
aws

,Unnamed: 0,지점번호,시각,평균 기온,최고 기온,최저 기온,평균 풍속,합성 풍속,합성 풍향,최대 순간 풍속,...,평균 현지기압,평균 해면기압,이슬점온도,10분 평균 시정,운고,위도,경도,해발고도,권역,weather_label
0,0,90,2014-07-01 01:00:00,20.3,20.5,20.0,0.7,0.6,285.6,1.7,...,1006.9,1009.0,20.1,0.0,7620.0,38.2509,128.5647,17.53,강원도,"['0', '0', '0', '0', '0', '0', '0', '0', '0', ..."
1,1,90,2014-07-01 02:00:00,20.1,20.3,19.9,0.8,0.7,310.0,1.7,...,1007.2,1009.3,19.9,0.0,7620.0,38.2509,128.5647,17.53,강원도,"['0', '0', '0', '0', '0', '0', '0', '0', '0', ..."
2,2,90,2014-07-01 03:00:00,19.9,20.0,19.7,1.2,1.1,306.1,2.5,...,1007.4,1009.5,19.6,0.0,45.0,38.2509,128.5647,17.53,강원도,"['0', '0', '0', '0', '0', '0', '0', '0', '0', ..."
3,3,90,2014-07-01 04:00:00,19.6,19.7,19.4,0.4,0.2,353.8,1.6,...,1007.6,1009.7,19.5,0.0,45.0,38.2509,128.5647,17.53,강원도,"['0', '0', '0', '0', '0', '0', '0', '0', '0', ..."
4,4,90,2014-07-01 05:00:00,19.5,19.7,19.3,0.5,0.4,325.3,1.2,...,1008.2,1010.3,19.2,0.0,45.0,38.2509,128.5647,17.53,강원도,"['0', '0', '0', '0', '0', '0', '0', '0', '0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467227,467227,989,2014-07-31 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2579,126.3299,90.00,제주도,"['0', '0', '1', '0', '0', '0', '0', '0', '0', ..."
467228,467228,989,2014-07-31 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2579,126.3299,90.00,제주도,"['0', '0', '1', '0', '0', '0', '0', '0', '0', ..."
467229,467229,989,2014-07-31 22:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2579,126.3299,90.00,제주도,"['0', '0', '1', '1', '0', '0', '0', '0', '0', ..."
467230,467230,989,2014-07-31 23:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2579,126.3299,90.00,제주도,"['0', '0', '1', '1', '0', '0', '0', '0', '0', ..."
467231,467231,989,2014-08-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2579,126.3299,90.00,제주도,"['0', '0', '1', '1', '0', '0', '0', '0', '0', ..."

In [14]:
# 분석에 사용할 feature 선택
csv_features = ['평균 기온', '최고 기온', '최저 기온', '평균 풍속', '합성 풍속', '합성 풍향', '최대 순간 풍속', '최대 순간 풍속 풍향', 
                '평균 전운량', '합계 강수량', '평균 현지기압', '평균 해면기압', '이슬점온도', '10분 평균 시정', '운고']

csv_files = sorted(glob('/raid/workspace/honghee/data_weather/train_x/aws/*/*.csv'))
# print(csv_files)

temp_csv = pd.read_csv(csv_files[0])[csv_features]
# temp_csv = temp_csv.replace('-',np.nan).dropna()
max_arr, min_arr = temp_csv.max().to_numpy(), temp_csv.min().to_numpy()

# print(temp_csv)
# print(max_arr)
# print(min_arr)

# feature 별 최대값, 최솟값 계산
for csv in tqdm(csv_files[1:69]):
    temp_csv = pd.read_csv(csv)[csv_features]
    temp_csv = temp_csv.replace('-',np.nan).dropna()
    if len(temp_csv) == 0:
        continue
    temp_csv = temp_csv.astype(float)
    temp_max, temp_min = temp_csv.max().to_numpy(), temp_csv.min().to_numpy()
    max_arr = np.max([max_arr,temp_max], axis=0)
    min_arr = np.min([min_arr,temp_min], axis=0)

# feature 별 최대값, 최솟값 dictionary 생성
csv_feature_dict = {csv_features[i]:[min_arr[i], max_arr[i]] for i in range(len(csv_features))}
csv_feature_dict

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68/68 [00:33<00:00,  2.05it/s]

{'평균 기온': [-24.7, 40.0],
 '최고 기온': [-24.1, 58.0],
 '최저 기온': [-199.9, 39.2],
 '평균 풍속': [0.0, 43.7],
 '합성 풍속': [0.0, 44.1],
 '합성 풍향': [0.0, 360.0],
 '최대 순간 풍속': [0.0, 941.1],
 '최대 순간 풍속 풍향': [0.0, 948.4],
 '평균 전운량': [-12.4, 322.0],
 '합계 강수량': [0.0, 485.0],
 '평균 현지기압': [835.2, 1038.4],
 '평균 해면기압': [843.9, 1043.9],
 '이슬점온도': [-46.7, 31.8],
 '10분 평균 시정': [0.0, 65470.0],
 '운고': [0.0, 14700.0]}

In [5]:
class CustomDataset(Dataset):
    def __init__(self, files, labels=None, mode='train'):
        self.mode = mode
        self.files = files
        self.csv_feature_dict = csv_feature_dict
        self.csv_feature_check = [0]*len(self.files)
        self.csv_features = [None]*len(self.files)
        self.max_len = 24 * 6
#         self.label_encoder = label_encoder

    def __len__(self):
        return len(self.files)
    
    def __getitem__(self, i):
        file = self.files[i]
        file_name = file.split('/')[-1]
        
        # csv
        if self.csv_feature_check[i] == 0:
            csv_path = f'{file}/{file_name}.csv'
            df = pd.read_csv(csv_path)[self.csv_feature_dict.keys()]
            df = df.replace('-', 0)
            # MinMax scaling
            for col in df.columns:
                df[col] = df[col].astype(float) - self.csv_feature_dict[col][0]
                df[col] = df[col] / (self.csv_feature_dict[col][1]-self.csv_feature_dict[col][0])
            # zero padding
            pad = np.zeros((self.max_len, len(df.columns)))
            length = min(self.max_len, len(df))
            pad[-length:] = df.to_numpy()[-length:]
            # transpose to sequential data
            csv_feature = pad.T
            self.csv_features[i] = csv_feature
            self.csv_feature_check[i] = 1
        else:
            csv_feature = self.csv_features[i]